{% set name = "standardese" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}.tgz
  sha256: b932cb757e43d9d2c93072c6e833306aff050e04910072e3e809c1a67426331c
  patches:
    - 0001-fix-compile-error-on-windows.patch
    # upstream at https://github.com/foonathan/cppast/pull/104
    - 0003-no-warn-as-error.patch

build:
  number: 0
  skip: true  # [win and vc<14]
  run_exports:
    # standardese uses semantic versioning
    - {{ pin_subpackage("standardese") }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  host:
    - boost-cpp
    - clangdev
  run:
    - {{ pin_compatible('libclang') }}
    - {{ pin_compatible('clangxx') }}
    - boost-cpp

test:
  files:
    - sample.h
  commands:
    - standardese sample.h

about:
  home: https://standardese.github.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The nextgen Doxygen for C++
  doc_url: https://standardese.github.io/
  dev_url: https://github.com/standardese/standardese

extra:
  recipe-maintainers:
    - saraedum
