{% set name = "standardese" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tgz
  sha256: 4f27dbba6d577636a622dd0dc13257e8f11ed7bab5c41808bc0943720c2cc842
  patches:
    - 0001-Actually-install-standardese-in-make-install.patch
    - 0002-boost-link-dynamic.patch
    # upstream at https://github.com/foonathan/cppast/pull/104
    - 0003-no-warn-as-error.patch

build:
  number: 2
  skip: true  # [win and vc<14]
  run_exports:
    # standardese uses semantic versioning
    - {{ pin_subpackage("standardese") }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  host:
    - boost-cpp
    - clangdev
  run:
    - {{ pin_compatible('libclang') }}
    - {{ pin_compatible('clangxx') }}
    - boost-cpp

test:
  files:
    - sample.h
  commands:
    - standardese sample.h

about:
  home: https://standardese.github.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'The nextgen Doxygen for C++'
  doc_url: https://standardese.github.io/
  dev_url: https://github.com/standardese/standardese

extra:
  recipe-maintainers:
    - saraedum
